# Generated by Django 5.2.14 on 2026-05-18 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='The URL of the code repository (e.g., GitHub, GitLab)', unique=True)),
                ('name', models.CharField(blank=True, help_text='A human-friendly name for the repository (optional)', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url'], name='idx_repository_url')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(help_text='The research question or prompt')),
                ('final_answer', models.TextField(blank=True, help_text='The final synthesized answer to the research question', null=True)),
                ('token_usage', models.IntegerField(default=0, help_text='The number of tokens used in the research session')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agent.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(help_text='The name of the tool used for the finding', max_length=100)),
                ('input_data', models.JSONField(help_text='The parameters passed to the tool')),
                ('output_data', models.TextField(help_text='The raw output/code returned by the tool')),
                ('conclusion', models.TextField(blank=True, help_text="The agent's synthesized note on this finding", null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='agent.researchsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
