# Generated by Django 5.2.14 on 2026-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['session', 'created_at'], name='idx_finding_session_created'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['tool_name'], name='idx_finding_tool_name'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['repository', '-created_at'], name='idx_session_repo_created'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['-created_at'], name='idx_session_created_at'),
        ),
        migrations.AddConstraint(
            model_name='researchsession',
            constraint=models.UniqueConstraint(fields=('repository', 'question'), name='unique_session_per_repo_question'),
        ),
    ]
